version: "2"
services:
  postgresql:
    container_name: postgresql
    hostname: postgresql
    restart: on-failure
    build: postgresql
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=vact
      - POSTGRES_PASSWORD=sa
    networks:
      - vact
    command: postgres 
volumes:
  postgresql:
networks:
  vact:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
